object ComposeLibs {
    const val Bom = "androidx.compose:compose-bom:${Versions.composeBom}"
    const val UI = "androidx.compose.ui:ui"
    const val Graphics = "androidx.compose.ui:ui-graphics"
    const val Preview = "androidx.compose.ui:ui-tooling-preview"
    const val UITooling = "androidx.compose.ui:ui-tooling"
    const val Material = "androidx.compose.material:material:${Versions.composeMaterial}"
    const val Material3 = "androidx.compose.material3:material3:${Versions.composeMaterial3}"
    const val Material3WindowSize = "androidx.compose.material3:material3-window-size-class:${Versions.composeMaterial3}"
    const val MaterialIconCore = "androidx.compose.material:material-icons-core:${Versions.composeMaterial}"
    const val MaterialIconExtended = "androidx.compose.material:material-icons-extended:${Versions.composeMaterial}"
    const val LiveData = "androidx.compose.runtime:runtime-livedata:${Versions.composeLiveData}"
    const val Foundation = "androidx.compose.foundation:foundation:${Versions.composeFoundation}"
    const val Animation = "androidx.compose.animation:animation:${Versions.composeAnimation}"
    const val Activity = "androidx.activity:activity-compose:${Versions.activityCompose}"
    const val ViewModel = "androidx.lifecycle:lifecycle-viewmodel-compose:${Versions.composeViewModel}"
    const val Lifecycle = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.composeViewModel}"
    const val LifecycleRuntime = "androidx.lifecycle:lifecycle-runtime-compose:${Versions.composeViewModel}"
    const val ConstraintLayout = "androidx.constraintlayout:constraintlayout-compose:${Versions.composeConstraintLayout}"
    const val Navigation = "androidx.navigation:navigation-compose:${Versions.composeNavigation}"
    const val Coil = "io.coil-kt:coil-compose:${Versions.coilVersion}"
    const val ThemeAdapter = "com.google.accompanist:accompanist-themeadapter-material:${Versions.accompanistVersion}"
    const val SystemUIController = "com.google.accompanist:accompanist-systemuicontroller:${Versions.accompanistVersion}"
    const val Permission = "com.google.accompanist:accompanist-permissions:${Versions.accompanistVersion}"
    const val Lottie = "com.airbnb.android:lottie-compose:4.0.0"
}