object Versions {
    const val kotlinVersion = "1.9.24" // Kotlin Compiler
    const val androidApplication = "8.7.3" // application
    const val androidLibrary = "8.7.3" // android library
    const val artifactory = "4.32.0"
    const val googleServicePlugin = "4.4.0"
    const val navigationSafeargs = "2.5.0"
    const val appcompat = "1.7.0" //1.6.1 appcompat
    const val googleMaterial = "1.12.0" //1.6.1 material
    const val kotlinxCoroutines = "1.7.2"
    const val lifecycleRuntimeKtx = "2.8.7" //2.6.1
    const val lifecycleProcess = "2.8.5"
    const val lifecycle = "2.6.2"
    const val activityCompose = "1.9.3" //1.8.2
    const val composeMaterial = "1.5.4"
    const val composeLiveData = "1.5.4"
    const val composeMaterial3 = "1.1.2"
    const val composeAnimation = "1.5.4"
    const val composeFoundation = "1.6.4"
    const val composeBom = "2024.12.01"
    const val composeConstraintLayout = "1.0.1"
    const val composeNavigation = "2.7.6"
    const val composeViewModel = "2.6.2"
    const val junitTest = "4.13.2"
    const val androidxJunitTest = "1.2.1" //1.1.5 junitVersion
    const val espressoTest = "3.6.1" //3.5.1 espressoCore
    const val retrofit = "2.9.0"
    const val retrofitCoroutinesAdapter = "0.9.2"
    const val okhttp = "4.9.3"
    const val hiltAndroid = "2.50"
    const val hiltAndroidCompiler = "2.50"
    const val hiltCompiler = "1.2.0"
    const val fragmentKtx = "1.5.5"
    const val activityKtx = "1.5.1"
    const val timber = "5.0.1"
    const val retrofitMoshi = "2.9.0"
    const val moshi = "1.12.0"
    const val constraintLayout = "2.1.4"
    const val navigationFragment = "2.7.6"
    const val multidex = "2.0.1"
    const val firebaseBom = "33.7.0"
    const val securityCrypto = "1.1.0-alpha06"
    const val coilVersion = "2.2.2"
    const val chuckerVersion = "3.5.2"
    const val accompanistVersion = "0.30.1"
    const val coreVersion = "1.15.0" //1.12.0 coreKtx
    const val firebaseCrashlytics = "2.9.9"
    const val lottie = "3.4.0"
    const val smsVerification = "20.4.0"
    const val smsPhoneVerification = "18.0.1"
    const val webKitVersion = "1.9.0"
    const val googleLocation = "21.3.0"
    const val mockkVersion = "1.13.13"
    const val coroutineTestVersion = "1.6.4"
    const val turbineTestVersion = "0.12.1"
    const val composeAndroidCompilerVersion = "1.5.14"
    const val roomVersion = "2.6.1"
    const val inAppReview = "2.0.2"
}