package com.skyvo.mobile.core.uikit.theme

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

data class AppCoreColorScheme(
    val background: Color = Color.Unspecified,
    val onBackground: Color = Color.Unspecified,
    val primary: Color = Color.Unspecified,
    val onPrimary: Color = Color.Unspecified,
    val secondary: Color = Color.Unspecified,
    val surface: Color = Color.Unspecified,
    val onSurface: Color = Color.Unspecified,
    val colorSurfaceBase: Color = Color.Unspecified,
    val colorTextMain: Color = Color.Unspecified,
    val colorTextOnPrimary: Color = Color.Unspecified,
    val colorTextOnSecondary: Color = Color.Unspecified,
    val colorBackgroundButtonPrimaryDefault: Color = Color.Unspecified,
    val colorBackgroundButtonSecondaryDefault: Color = Color.Unspecified,
    val colorBackgroundButtonPrimaryDisabled: Color = Color.Unspecified,
    val colorBackgroundButtonSecondaryDisabled: Color = Color.Unspecified,
    val colorTextDisabled: Color = Color.Unspecified,
    val colorBorderInputsDefault: Color = Color.Unspecified,
    val colorBorderSelected: Color = Color.Unspecified,
    val colorBackgroundSelected: Color = Color.Unspecified,
    val colorCheckBoxChecked: Color = Color.Unspecified,
    val colorCheckBoxUnchecked: Color = Color.Unspecified,
    val colorTextSubtler: Color = Color.Unspecified,
    val colorIcon: Color = Color.Unspecified,
    val colorIconBackground: Color = Color.Unspecified,
    val colorBackgroundDecorativeGreySubtler: Color = Color.Unspecified,
    val colorBackgroundInputsToggleBaseOff: Color = Color.Unspecified,
    val colorRadioButtonChecked: Color = Color.Unspecified,
    val colorRadioButtonUnChecked: Color = Color.Unspecified,
    val colorTextInformationWarningBold: Color = Color.Unspecified,
    val colorBackgroundInputsTextBox: Color = Color.Unspecified,
    val colorBorderInputsSelected: Color = Color.Unspecified,
    val colorBackgroundInformationSubtle: Color = Color.Unspecified,
    val colorIconBrandBoldRed: Color = Color.Unspecified,
    val colorProgressBarForeground: Color = Color.Unspecified,
    val colorProgressBarBackground: Color = Color.Unspecified,
)

val AppLightColors = AppCoreColorScheme(
    background = Color(0xFFFFFFFE),
    onBackground = Color(0xFF14161B),
    primary = Color(0xFFE8C506),
    secondary = Color(0xFF42226E),
    onPrimary = Color(0xFFE8C506),
    surface = Color(0xFFFFFFFE),
    onSurface = Color(0xFF14161B),
    colorSurfaceBase = Color(0xFFFFFFFE),
    colorTextMain = Color(0xFF14161B),
    colorTextOnPrimary = Color(0xFF14161B),
    colorTextOnSecondary = Color(0xFF14161B),
    colorBackgroundButtonPrimaryDefault = Color(0xFFE8C506),
    colorBackgroundButtonSecondaryDefault = Color(0xFFFFFFFE),
    colorBackgroundButtonPrimaryDisabled = Color(0x73E8C506),
    colorBackgroundButtonSecondaryDisabled = Color(0xFFFFFFFE),
    colorTextDisabled = Color(0xFFFFFFFF),
    colorBorderInputsDefault = Color(0xFF8C8C8C),
    colorBorderSelected = Color(0xFFF1CC06),
    colorBackgroundSelected = Color(0xFFFFFFFE),
    colorCheckBoxChecked = Color(0xFFFFEB3B),
    colorCheckBoxUnchecked = Color(0xFFDADACE),
    colorTextSubtler = Color(0xFF8D8DA6),
    colorIcon = Color(0xFF14161B),
    colorIconBackground = Color(0xFFD2D2D2),
    colorBackgroundDecorativeGreySubtler = Color(0xFF919191),
    colorBackgroundInputsToggleBaseOff = Color(0x9E021C5D),
    colorRadioButtonChecked = Color(0xFFE1F620),
    colorRadioButtonUnChecked = Color(0xFFF1F1DB),
    colorTextInformationWarningBold = Color(0xFFE13B51),
    colorBackgroundInputsTextBox = Color(0xFFFFFFFE),
    colorBorderInputsSelected = Color(0x37092B49),
    colorBackgroundInformationSubtle = Color(0x48AFA9A9),
    colorIconBrandBoldRed = Color(0xD39D031B),
    colorProgressBarForeground = Color(0xFFFFEB3B),
    colorProgressBarBackground = Color(0x48AFA9A9),
)

val AppDarkColors = AppCoreColorScheme(
    background = Color(0xFF14161B),
    onBackground = Color(0xFFFCFCFD),
    primary = Color(0xFFF1CC06),
    secondary = Color(0xFF7950C3),
    onPrimary = Color(0xFFF1CC06),
    surface = Color(0xFF14161B),
    onSurface = Color(0xFFFFFFFE),
    colorSurfaceBase = Color(0xFF14161B),
    colorTextMain = Color(0xFFFFFFFE),
    colorTextOnPrimary = Color(0xFF14161B),
    colorTextOnSecondary = Color(0xFFFFFFFE),
    colorBackgroundButtonPrimaryDefault = Color(0xFFF1CC06),
    colorBackgroundButtonSecondaryDefault = Color(0xFF313843),
    colorBackgroundButtonPrimaryDisabled = Color(0x59F1CC06),
    colorBackgroundButtonSecondaryDisabled = Color(0x4D313843),
    colorTextDisabled = Color(0xFFFFFFFF),
    colorBorderInputsDefault = Color(0xFF3D4357),
    colorBorderSelected = Color(0xFFF1CC06),
    colorBackgroundSelected = Color(0xFF1C1F26),
    colorCheckBoxChecked = Color(0xFFFFEB3B),
    colorCheckBoxUnchecked = Color(0xFFEAEAE2),
    colorTextSubtler = Color(0xFF83899F),
    colorIcon = Color(0xFFFFFFFE),
    colorIconBackground = Color(0xFF22252E),
    colorBackgroundDecorativeGreySubtler = Color(0xFFC2BFBF),
    colorBackgroundInputsToggleBaseOff = Color(0xFFC3D2EF),
    colorRadioButtonChecked = Color(0xFFE1F620),
    colorRadioButtonUnChecked = Color(0xFFF1F1DB),
    colorTextInformationWarningBold = Color(0xFFDE6F7E),
    colorBackgroundInputsTextBox = Color(0xFFF3ECED),
    colorBorderInputsSelected = Color(0xFFF3ECED),
    colorBackgroundInformationSubtle = Color(0xFFF1F1F1),
    colorIconBrandBoldRed = Color(0xD39D031B),
    colorProgressBarForeground = Color(0xFFFFEB3B),
    colorProgressBarBackground = Color(0x48AFA9A9),
)

val LocalAppColor = staticCompositionLocalOf { AppCoreColorScheme() }
